apiVersion: v2
name: kube-prometheus-stack
description: A Helm chart that references the official "kube-prometheus-stack" Helm chart.
type: application
version: 81.6.3
dependencies:
  - name: kube-prometheus-stack
    version: 81.6.3
    repository: https://prometheus-community.github.io/helm-charts
