st-charts:
- name: cert-manager
  dep_name: cert-manager
  version: 1.16.2
  repository: https://charts.jetstack.io
- name: cert-manager
  dep_name: cert-manager
  version: 1.17.2
  repository: https://charts.jetstack.io
- name: cert-manager
  dep_name: cert-manager
  version: 1.18.2
  repository: https://charts.jetstack.io
- name: cert-manager
  dep_name: cert-manager
  version: 1.19.2
  repository: https://charts.jetstack.io
