st-charts:
- name: keycloakx
  dep_name: keycloakx
  version: 7.1.7
  repository: https://codecentric.github.io/helm-charts
- name: keycloakx
  dep_name: keycloakx
  version: 7.1.8
  repository: https://codecentric.github.io/helm-charts
