apiVersion: v2
name: dapr
description: A Helm chart that references the official "dapr" Helm chart.
type: application
version: 1.16.9
dependencies:
  - name: dapr
    version: 1.16.9
    repository: https://dapr.github.io/helm-charts/
