apiVersion: v2
name: istio-gateway
description: A Helm chart that references the official "istio-gateway" Helm chart.
type: application
version: 1.28.3
dependencies:
  - name: gateway
    version: 1.28.3
    repository: https://istio-release.storage.googleapis.com/charts
