apiVersion: v2
name: valkey
description: A Helm chart that references the official "valkey" Helm chart.
type: application
version: 0.1.0
dependencies:
  - name: valkey
    version: 0.1.0
    repository: oci://ghcr.io/k0rdent/catalog/charts/
