apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: k0rdent-catalog-josca
  namespace: kcm-system
  labels:
    k0rdent.mirantis.com/managed: "true"
  annotations:
    helm.sh/hook: pre-install
    helm.sh/resource-policy: keep
spec:
  provider: generic
  type: oci
  url: oci://ghcr.io/josca/k0rdent-catalog/charts
---
apiVersion: k0rdent.mirantis.com/v1beta1
kind: ClusterTemplate
metadata:
  name: azure-standalone-cp-1-0-13-custom
  namespace: kcm-system
  annotations:
    helm.sh/resource-policy: keep
spec:
  helm:
    chartSpec:
      chart: azure-standalone-cp
      version: 1.0.13
      interval: 10m0s
      sourceRef:
        kind: HelmRepository
        name: k0rdent-catalog-josca
