apiVersion: k0rdent.mirantis.com/v1beta1
kind: ClusterDeployment
metadata:
  name: gcp-example-USER
  namespace: kcm-system
  labels:
    type: gcp
    group: demo
spec:
  template: gcp-standalone-cp-1-0-18
  credential: gcp-credential
  config:
    project: "GCP_PROJECT" # your GCP project
    region: "us-west1"
    controlPlane:
      instanceType: "e2-small"
      image: projects/ubuntu-os-cloud/global/images/ubuntu-2004-focal-v20250213
      publicIP: true
    controlPlaneNumber: 1
    worker:
      instanceType: "e2-medium"
      image: projects/ubuntu-os-cloud/global/images/ubuntu-2004-focal-v20250213
      publicIP: true
      rootVolumeSize: 16
    workersNumber: 1
