kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: adopted
nodes:
  - role: control-plane
    extraPortMappings:
      - containerPort: 80
        hostPort: 50080
        protocol: TCP
      - containerPort: 30080 # NodePort
        hostPort: 40080
        protocol: TCP
      - containerPort: 443
        hostPort: 50443
        protocol: TCP
      - containerPort: 30443 # NodePort
        hostPort: 40443
        protocol: TCP
      - containerPort: 5432
        hostPort: 55432
        protocol: TCP
