apiVersion: v2
name: runai-control-plane
description: A Helm chart that references the official "runai-control-plane" Helm chart.
type: application
version: 0.2.3
dependencies:
  - name: runai-control-plane
    version: 0.2.3
    repository: oci://registry.mirantis.com/k0rdent-ai/example/charts
