apiVersion: v2
name: datadog
description: A Helm chart that references the official "datadog" Helm chart.
type: application
version: 3.170.1
dependencies:
  - name: datadog
    version: 3.170.1
    repository: https://helm.datadoghq.com
