st-charts:
- name: mysql-operator
  dep_name: mysql-operator
  version: 2.2.3
  repository: https://mysql.github.io/mysql-operator
- name: mysql-operator
  dep_name: mysql-operator
  version: 2.2.7
  repository: https://mysql.github.io/mysql-operator
