st-charts:
- name: mongodb-community-operator
  dep_name: community-operator
  version: 0.12.0
  repository: https://mongodb.github.io/helm-charts
- name: mongodb-community-operator
  dep_name: community-operator
  version: 0.13.0
  repository: https://mongodb.github.io/helm-charts
