st-charts:
- name: cloudcasa
  dep_name: cloudcasa
  version: 3.4.4
  repository: https://catalogicsoftware.github.io/cloudcasa-helmchart/
- name: cloudcasa
  dep_name: cloudcasa
  version: 3.4.6
  repository: https://catalogicsoftware.github.io/cloudcasa-helmchart/
