opentelemetry-collector:
  opentelemetry-collector:
    image:
      repository: "otel/opentelemetry-collector-k8s"
    mode: daemonset # <daemonset|deployment|statefulset>

opentelemetry-operator:
  opentelemetry-operator:
    manager:
      collectorImage:
        repository: "otel/opentelemetry-collector-k8s"
    admissionWebhooks:
      certManager:
        enabled: false
      autoGenerateCert:
        enabled: true
