apiVersion: v2
name: kube-prometheus-stack
description: A Helm chart that references the official "kube-prometheus-stack" Helm chart.
type: application
version: 77.0.0
dependencies:
  - name: kube-prometheus-stack
    version: 77.0.0
    repository: https://prometheus-community.github.io/helm-charts
