apiVersion: v2
name: metallb
description: A Helm chart that references the official "metallb" Helm chart.
type: application
version: 0.15.3
dependencies:
  - name: metallb
    version: 0.15.3
    repository: https://metallb.github.io/metallb
