st-charts:
- name: kubecost
  dep_name: cost-analyzer
  version: 2.5.3
  repository: https://kubecost.github.io/cost-analyzer/
- name: kubecost
  dep_name: cost-analyzer
  version: 2.9.6
  repository: https://kubecost.github.io/cost-analyzer/
