st-charts:
- name: postgres-operator
  dep_name: postgres-operator
  version: 1.14.0
  repository: https://opensource.zalando.com/postgres-operator/charts/postgres-operator
- name: postgres-operator
  dep_name: postgres-operator
  version: 1.15.1
  repository: https://opensource.zalando.com/postgres-operator/charts/postgres-operator
