st-charts:
- name: gpu-operator
  dep_name: gpu-operator
  version: 24.9.2
  repository: https://helm.ngc.nvidia.com/nvidia
- name: gpu-operator
  dep_name: gpu-operator
  version: 25.3.0
  repository: https://helm.ngc.nvidia.com/nvidia
- name: gpu-operator
  dep_name: gpu-operator
  version: 25.10.0
  repository: https://helm.ngc.nvidia.com/nvidia
- name: gpu-operator
  dep_name: gpu-operator
  version: 25.10.1
  repository: https://helm.ngc.nvidia.com/nvidia
