st-charts:
  - name: runai-control-plane
    dep_name: runai-control-plane
    version: 0.3.0
    repository: oci://registry.mirantis.com/k0rdent-ai/example/charts
  - name: runai-control-plane
    dep_name: runai-control-plane
    version: 0.2.3
    repository: oci://registry.mirantis.com/k0rdent-ai/example/charts
    
