apiVersion: v2
name: kiali-operator
description: A Helm chart that references the official "kiali-operator" Helm chart.
type: application
version: 2.21.0
dependencies:
  - name: kiali-operator
    version: 2.21.0
    repository: https://kiali.org/helm-charts
