st-charts:
- name: jenkins
  dep_name: jenkins
  version: 5.8.84
  repository: https://charts.jenkins.io
- name: jenkins
  dep_name: jenkins
  version: 5.8.116
  repository: https://charts.jenkins.io
