apiVersion: v2
name: kgateway
description: A Helm chart that references the official "kgateway" Helm chart.
type: application
version: v2.1.1
dependencies:
  - name: kgateway
    version: v2.1.1
    repository: oci://cr.kgateway.dev/kgateway-dev/charts
