st-charts:
- name: velero
  dep_name: velero
  version: 8.1.0
  repository: https://vmware-tanzu.github.io/helm-charts/
- name: velero
  dep_name: velero
  version: 10.0.10
  repository: https://vmware-tanzu.github.io/helm-charts/
- name: velero
  dep_name: velero
  version: 11.1.0
  repository: https://vmware-tanzu.github.io/helm-charts/
- name: velero
  dep_name: velero
  version: 11.3.2
  repository: https://vmware-tanzu.github.io/helm-charts/
