apiVersion: v2
name: grafana
description: A Helm chart that references the official "grafana" Helm chart.
type: application
version: 10.5.15
dependencies:
  - name: grafana
    version: 10.5.15
    repository: https://grafana.github.io/helm-charts
