st-charts:
- name: prometheus
  dep_name: prometheus
  version: 27.5.1
  repository: https://prometheus-community.github.io/helm-charts
- name: prometheus
  dep_name: prometheus
  version: 28.9.0
  repository: https://prometheus-community.github.io/helm-charts
