st-charts:
- name: external-secrets
  dep_name: external-secrets
  version: 0.11.0
  repository: https://charts.external-secrets.io
- name: external-secrets
  dep_name: external-secrets
  version: 0.18.2
  repository: https://charts.external-secrets.io
- name: external-secrets
  dep_name: external-secrets
  version: 1.2.1
  repository: https://charts.external-secrets.io
- name: external-secrets
  dep_name: external-secrets
  version: 2.0.0
  repository: https://charts.external-secrets.io
