apiVersion: v2
name: clearml-serving
description: A Helm chart that references the official "clearml-serving" Helm chart.
type: application
version: 1.5.10
dependencies:
  - name: clearml-serving
    version: 1.5.10
    repository: https://clearml.github.io/clearml-helm-charts
