apiVersion: v2
name: kube-arangodb
description: A Helm chart that references the official "kube-arangodb" Helm chart.
type: application
version: 1.4.0
dependencies:
  - name: kube-arangodb
    version: 1.4.0
    repository: https://arangodb.github.io/kube-arangodb
