apiVersion: v2
name: cert-manager
description: A Helm chart that references the official "cert-manager" Helm chart.
type: application
version: 1.19.2
dependencies:
  - name: cert-manager
    version: 1.19.2
    repository: https://charts.jetstack.io
