apiVersion: v2
name: pypiserver
description: A Helm chart that references the official "pypiserver" Helm chart.
type: application
version: 0.1.8
dependencies:
  - name: pypiserver
    version: 0.1.8
    repository: https://community-charts.github.io/helm-charts
