apiVersion: v2
name: envoy-gateway
description: A Helm chart that references the official "envoy-gateway" Helm chart.
type: application
version: 1.3.2
dependencies:
  - name: gateway-helm
    version: 1.3.2
    repository: oci://docker.io/envoyproxy
