apiVersion: v2
name: velero
description: A Helm chart that references the official "velero" Helm chart.
type: application
version: 11.1.1
dependencies:
  - name: velero
    version: 11.1.1
    repository: https://vmware-tanzu.github.io/helm-charts/
