st-charts:
- name: helm-soperator
  dep_name: helm-soperator
  version: 1.22.1
  repository: oci://cr.eu-north1.nebius.cloud/soperator
- name: helm-slurm-cluster
  dep_name: helm-slurm-cluster
  version: 1.22.1
  repository: oci://cr.eu-north1.nebius.cloud/soperator
