apiVersion: v2
name: helm-slurm-cluster
description: A Helm chart that references the official "helm-slurm-cluster" Helm chart.
type: application
version: 1.22.1
dependencies:
  - name: helm-slurm-cluster
    version: 1.22.1
    repository: oci://cr.eu-north1.nebius.cloud/soperator
