apiVersion: v2
name: prometheus
description: A Helm chart that references the official "prometheus" Helm chart.
type: application
version: 28.9.0
dependencies:
  - name: prometheus
    version: 28.9.0
    repository: https://prometheus-community.github.io/helm-charts
