ingress-nginx:
  ingress-nginx:
    controller:
      service:
        annotations:
          service.beta.kubernetes.io/azure-load-balancer-health-probe-request-path: /healthz
      hostPort:
        enabled: true
    tcp:
      5432: "postgresql/postgresql:5432"
      5433: "postgresql/postgresql-read:5432"

postgresql:
  postgresql:
    global:
      security:
        allowInsecureImages: true
    image:
      repository: bitnamilegacy/postgresql
    auth:
      postgresPassword: pgpasswd
      username: user
      password: passwd
      database: pgdb
    readReplicas:
      replicaCount: 2
