apiVersion: k0rdent.mirantis.com/v1alpha1
kind: ServiceTemplate
metadata:
  name: metallb-0-15-2
  annotations:
    helm.sh/resource-policy: keep
spec:
  helm:
    chartSpec:
      chart: metallb
      version: 0.15.2
      interval: 10m0s
      sourceRef:
        kind: HelmRepository
        name: k0rdent-catalog
