apiVersion: v2
name: gitlab
description: A Helm chart that references the official "gitlab" Helm chart.
type: application
version: 9.5.1
dependencies:
  - name: gitlab
    version: 9.5.1
    repository: https://charts.gitlab.io/
