apiVersion: v2
name: jupyterhub
description: A Helm chart that references the official "jupyterhub" Helm chart.
type: application
version: 4.3.2
dependencies:
  - name: jupyterhub
    version: 4.3.2
    repository: https://jupyterhub.github.io/helm-chart/
