st-charts:
- name: ingress-nginx
  dep_name: ingress-nginx
  version: 4.11.0
  repository: https://kubernetes.github.io/ingress-nginx
- name: ingress-nginx
  dep_name: ingress-nginx
  version: 4.11.3
  repository: https://kubernetes.github.io/ingress-nginx
- name: ingress-nginx
  dep_name: ingress-nginx
  version: 4.11.5
  repository: https://kubernetes.github.io/ingress-nginx
- name: ingress-nginx
  dep_name: ingress-nginx
  version: 4.12.3
  repository: https://kubernetes.github.io/ingress-nginx
- name: ingress-nginx
  dep_name: ingress-nginx
  version: 4.13.0
  repository: https://kubernetes.github.io/ingress-nginx
- name: ingress-nginx
  dep_name: ingress-nginx
  version: 4.13.2
  repository: https://kubernetes.github.io/ingress-nginx
