apiVersion: v2
name: open-webui
description: A Helm chart that references the official "open-webui" Helm chart.
type: application
version: 8.12.3
dependencies:
  - name: open-webui
    version: 8.12.3
    repository: https://helm.openwebui.com/
