apiVersion: v2
name: open-webui
description: A Helm chart that references the official "open-webui" Helm chart.
type: application
version: 10.2.1
dependencies:
  - name: open-webui
    version: 10.2.1
    repository: https://helm.openwebui.com/
