apiVersion: v2
name: keycloakx
description: A Helm chart that references the official "keycloakx" Helm chart.
type: application
version: 7.1.8
dependencies:
  - name: keycloakx
    version: 7.1.8
    repository: https://codecentric.github.io/helm-charts
