apiVersion: v2
name: network-operator
description: A Helm chart that references the official "network-operator" Helm chart.
type: application
version: 25.10.0
dependencies:
  - name: network-operator
    version: 25.10.0
    repository: https://helm.ngc.nvidia.com/nvidia
