apiVersion: v2
name: milvus
description: A Helm chart that references the official "milvus" Helm chart.
type: application
version: 5.0.14
dependencies:
  - name: milvus
    version: 5.0.14
    repository: https://zilliztech.github.io/milvus-helm/
