apiVersion: v2
name: opencost
description: A Helm chart that references the official "opencost" Helm chart.
type: application
version: 2.5.8
dependencies:
  - name: opencost
    version: 2.5.8
    repository: https://opencost.github.io/opencost-helm-chart
