st-charts:
- name: grafana
  dep_name: grafana
  version: 9.3.6
  repository: https://grafana.github.io/helm-charts
- name: grafana
  dep_name: grafana
  version: 10.1.0
  repository: https://grafana.github.io/helm-charts
- name: grafana-operator
  dep_name: grafana-operator
  version: v5.20.0
  repository: oci://ghcr.io/grafana/helm-charts
- name: grafana
  dep_name: grafana
  version: 10.5.15
  repository: https://grafana.github.io/helm-charts
