apiVersion: v2
name: opentelemetry-collector
description: A Helm chart that references the official "opentelemetry-collector" Helm chart.
type: application
version: 0.141.0
dependencies:
  - name: opentelemetry-collector
    version: 0.141.0
    repository: https://open-telemetry.github.io/opentelemetry-helm-charts
