apiVersion: v2
name: mongodb-community-operator
description: A Helm chart that references the official "mongodb-community-operator" Helm chart.
type: application
version: 0.13.0
dependencies:
  - name: community-operator
    version: 0.13.0
    repository: https://mongodb.github.io/helm-charts
