apiVersion: v2
name: falco
description: A Helm chart that references the official "falco" Helm chart.
type: application
version: 8.0.0
dependencies:
  - name: falco
    version: 8.0.0
    repository: https://falcosecurity.github.io/charts/
