st-charts:
- name: nats
  dep_name: nats
  version: 1.3.13
  repository: https://nats-io.github.io/k8s/helm/charts/
- name: nats
  dep_name: nats
  version: 2.12.4
  repository: https://nats-io.github.io/k8s/helm/charts/
