apiVersion: v2
name: grafana-operator
description: A Helm chart that references the official "grafana-operator" Helm chart.
type: application
version: v5.18.0
dependencies:
  - name: grafana-operator
    version: v5.18.0
    repository: oci://ghcr.io/grafana/helm-charts
