st-charts:
- name: gatekeeper
  dep_name: gatekeeper
  version: 3.17.1
  repository: https://open-policy-agent.github.io/gatekeeper/charts/
- name: gatekeeper
  dep_name: gatekeeper
  version: 3.21.1
  repository: https://open-policy-agent.github.io/gatekeeper/charts/
