st-charts:
- name: dell-container-storage-modules
  dep_name: container-storage-modules
  version: 1.8.0
  repository: https://dell.github.io/helm-charts
- name: dell-container-storage-modules
  dep_name: container-storage-modules
  version: 1.9.0
  repository: https://dell.github.io/helm-charts
