apiVersion: v2
name: kyverno
description: A Helm chart that references the official "kyverno" Helm chart.
type: application
version: 3.7.0
dependencies:
  - name: kyverno
    version: 3.7.0
    repository: https://kyverno.github.io/kyverno/
