st-charts:
- name: kube-prometheus-stack
  dep_name: kube-prometheus-stack
  version: 69.7.4
  repository: https://prometheus-community.github.io/helm-charts
- name: kube-prometheus-stack
  dep_name: kube-prometheus-stack
  version: 72.6.2
  repository: https://prometheus-community.github.io/helm-charts
- name: kube-prometheus-stack
  dep_name: kube-prometheus-stack
  version: 77.0.0
  repository: https://prometheus-community.github.io/helm-charts
