st-charts:
- name: kyverno
  dep_name: kyverno
  version: 3.2.6
  repository: https://kyverno.github.io/kyverno/
- name: kyverno
  dep_name: kyverno
  version: 3.4.4
  repository: https://kyverno.github.io/kyverno/
- name: kyverno
  dep_name: kyverno
  version: 3.5.2
  repository: https://kyverno.github.io/kyverno/
- name: kyverno
  dep_name: kyverno
  version: 3.7.0
  repository: https://kyverno.github.io/kyverno/
