apiVersion: v2
name: minio
description: A Helm chart that references the official "minio" Helm chart.
type: application
version: 17.0.21
dependencies:
  - name: minio
    version: 17.0.21
    repository: https://charts.bitnami.com/bitnami
