apiVersion: v2
name: jenkins
description: A Helm chart that references the official "jenkins" Helm chart.
type: application
version: 5.8.139
dependencies:
  - name: jenkins
    version: 5.8.139
    repository: https://charts.jenkins.io
