apiVersion: v2
name: kubeflow-spark-operator
description: A Helm chart that references the official "kubeflow-spark-operator" Helm chart.
type: application
version: 2.4.0
dependencies:
  - name: spark-operator
    version: 2.4.0
    repository: https://kubeflow.github.io/spark-operator
