st-charts:
- name: qdrant
  dep_name: qdrant
  version: 1.15.4
  repository: https://qdrant.github.io/qdrant-helm
- name: qdrant
  dep_name: qdrant
  version: 1.16.3
  repository: https://qdrant.github.io/qdrant-helm
