apiVersion: v2
name: ingress-nginx
description: A Helm chart that references the official "ingress-nginx" Helm chart.
type: application
version: 4.14.3
dependencies:
  - name: ingress-nginx
    version: 4.14.3
    repository: https://kubernetes.github.io/ingress-nginx
