st-charts:
- name: dex
  dep_name: dex
  version: 0.19.1
  repository: https://charts.dexidp.io
- name: dex
  dep_name: dex
  version: 0.23.0
  repository: https://charts.dexidp.io
- name: dex
  dep_name: dex
  version: 0.24.0
  repository: https://charts.dexidp.io
